# Generated by Django 5.2.5 on 2025-08-26 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("turn", models.CharField(default="X", max_length=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("p", "in progress"),
                            ("w1", "p1 won"),
                            ("w2", "p2 won"),
                            ("d", "draw"),
                        ],
                        default="p",
                        max_length=2,
                    ),
                ),
                ("board", models.CharField(default="         ", max_length=9)),
                (
                    "player1_symbol",
                    models.CharField(
                        choices=[("X", "X"), ("O", "O")], default="X", max_length=1
                    ),
                ),
                (
                    "player2_symbol",
                    models.CharField(
                        choices=[("X", "X"), ("O", "O")], default="O", max_length=1
                    ),
                ),
                (
                    "player1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
